export const SWITCH_THEME = "SWITCH_THEME";
export const SET_THEME = "SET_THEME";
export const SET_SELECTED = "SET_SELECTED";
export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const FILTER_COUNTRIES = "FILTER_COUNTRIES";
